/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import control.GraficoControl;
import control.MunicipioControler;
import java.awt.BorderLayout;
import model.atributosGrafico;

/**
 *
 * @author mathe
 */
public class FrmGrafico extends javax.swing.JFrame {

    /**
     * Creates new form FrmGrafico
     */
    public FrmGrafico(String nome, String id) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        
        atributosGrafico atributo;
        GraficoControl grafico = new GraficoControl(id);
        
        atributo = GraficoControl.buscaBancoDeDados(nome);
        
        this.frmgrafico.setLayout(new BorderLayout());
        this.frmgrafico.add(grafico.criarGrafico(atributo));
         
        
    }

    public FrmGrafico() {
         //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmgrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout frmgraficoLayout = new javax.swing.GroupLayout(frmgrafico);
        frmgrafico.setLayout(frmgraficoLayout);
        frmgraficoLayout.setHorizontalGroup(
            frmgraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frmgraficoLayout.setVerticalGroup(
            frmgraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmgrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmgrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel frmgrafico;
    // End of variables declaration//GEN-END:variables
}
